"""empty message

Revision ID: 3e87894e575a
Revises: 
Create Date: 2020-08-07 13:07:37.059598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e87894e575a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.String(length=240), nullable=True))
    op.create_index(op.f('ix_comments_date_posted'), 'comments', ['date_posted'], unique=False)
    op.drop_column('comments', 'message')
    op.add_column('users', sa.Column('github', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_github'), 'users', ['github'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github'), table_name='users')
    op.drop_column('users', 'github')
    op.add_column('comments', sa.Column('message', sa.CHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_comments_date_posted'), table_name='comments')
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
